-- ============================================================
-- HATLY — توثيق جداول Push Notifications (fcm_tokens + push_subscriptions)
-- ============================================================
-- سبب هذا الملف:
-- الجدولان دول اتعملوا يدويًا من Supabase Dashboard / SQL Editor في وقت
-- سابق، ومكانوش موثّقين في أي migration بالـ repo. لو حصل reset للـ DB،
-- أو تم تشغيل supabase/schema.sql على مشروع جديد (staging مثلاً)، الجدولان
-- دول (وبالتالي كل منطق push notifications في lib/sendPushToUser.js
-- و app/api/push/*) هيقعوا بالكامل لأنهم مش هيكونوا موجودين.
--
-- الملف ده توثيقي بحت: بيعكس الـ schema الفعلي الموجود حاليًا على DB
-- الإنتاج زي ما هو بالظبط، بعد التأكد منه عبر استعلامات قراءة فقط على:
--   - information_schema.columns  (الأعمدة، الأنواع، الـ defaults)
--   - pg_constraint                (PK / UNIQUE / FK بالتفصيل)
--   - pg_class.relrowsecurity      (هل RLS مفعّل)
--   - pg_policies                  (الـ policies الفعلية)
--   - pg_publication_tables        (هل realtime مفعّل)
--
-- الملف آمن للتشغيل على DB فيه الجدولين دول بالفعل (كل شيء IDEMPOTENT عبر
-- IF NOT EXISTS / DROP POLICY IF EXISTS)، ومصمم يشتغل بنفس النتيجة على
-- مشروع Supabase جديد فاضي.
-- ============================================================


-- ============================================================
-- 1) fcm_tokens
--    توكنات إشعارات تطبيق الموبايل (Firebase Cloud Messaging).
--    نفس التوكن (نفس الجهاز) ممكن ينتقل من مستخدم لآخر (upsert بـ
--    onConflict: "token" في app/api/push/fcm-subscribe/route.js) —
--    عشان كده UNIQUE(token) مش UNIQUE(user_id, token).
-- ============================================================
create table if not exists public.fcm_tokens (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles(id) on delete cascade,
  token      text not null,
  created_at timestamptz not null default now(),

  constraint fcm_tokens_token_key unique (token)
);

alter table public.fcm_tokens enable row level security;

-- ملاحظة موثّقة (مش خطأ): لا توجد أي policies معرّفة فعليًا على هذا الجدول
-- في الإنتاج حاليًا (تأكدنا منه عبر pg_policies، رجع 0 صفوف). بما إن RLS
-- مفعّل بدون أي policy، فكل الوصول ممنوع تلقائيًا لأي role غير service_role.
-- هذا متوافق مع الكود الفعلي: كل قراءة/كتابة على الجدول ده في
-- app/api/push/fcm-subscribe/route.js و logout-cleanup/route.js و
-- lib/sendPushToUser.js بتتم حصريًا عبر supabaseAdmin (service role key)،
-- اللي بيتخطى RLS بالكامل بطبيعته. لا يوجد أي مسار كود يعتمد على anon/
-- authenticated key للوصول المباشر لهذا الجدول.
--
-- لا نضيف هنا أي policy جديدة عمدًا — إضافة policy الآن تُعتبر تغييرًا
-- فعليًا في السلوك الأمني، مش مجرد توثيق، وخارج نطاق هذا الملف.


-- ============================================================
-- 2) push_subscriptions
--    اشتراكات Web Push (المتصفح). نفس منطق fcm_tokens: نفس الجهاز/
--    endpoint ممكن ينتقل بين حسابات (upsert بـ onConflict: "endpoint"
--    في app/api/push/subscribe/route.js).
-- ============================================================
create table if not exists public.push_subscriptions (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  endpoint   text not null,
  p256dh     text not null,
  auth       text not null,
  created_at timestamptz not null default now(),

  constraint push_subscriptions_endpoint_key unique (endpoint)
);

alter table public.push_subscriptions enable row level security;

-- الـ policies الأربعة موجودة فعليًا في الإنتاج (تأكدنا منها عبر
-- pg_policies)، بتسمح لصاحب الاشتراك يدير اشتراكاته بنفسه مباشرة لو
-- احتاج الكود مستقبلًا يستخدم anon/authenticated key بدل service role.
-- بنعيد إنشاءها هنا بنمط idempotent (drop then create) عشان يفضل
-- الملف قابل لإعادة التشغيل بدون أخطاء.

drop policy if exists "Users can view own push subscriptions" on public.push_subscriptions;
create policy "Users can view own push subscriptions"
  on public.push_subscriptions
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own push subscriptions" on public.push_subscriptions;
create policy "Users can insert own push subscriptions"
  on public.push_subscriptions
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own push subscriptions" on public.push_subscriptions;
create policy "Users can update own push subscriptions"
  on public.push_subscriptions
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own push subscriptions" on public.push_subscriptions;
create policy "Users can delete own push subscriptions"
  on public.push_subscriptions
  for delete
  to authenticated
  using (auth.uid() = user_id);


-- ============================================================
-- ملاحظات توثيقية إضافية (لا تتطلب أي إجراء الآن):
--
-- 1) عدم تناسق في مرجع الـ Foreign Key:
--    fcm_tokens.user_id         -> public.profiles(id)
--    push_subscriptions.user_id -> auth.users(id)
--    الاثنان صحيحان عمليًا (profiles.id نفسه FK على auth.users.id)،
--    لكنه تصميم غير موحّد بين الجدولين. يستاهل توحيد لاحقًا كتحسين
--    منفصل، مش جزء من هذا التوثيق.
--
-- 2) Realtime غير مفعّل على أي من الجدولين (تأكدنا عبر
--    pg_publication_tables) — متوافق مع الاستخدام الحالي، الجدولان
--    بيُقرآن فقط عبر lib/sendPushToUser.js وقت إرسال push، مش عبر
--    اشتراك realtime في الواجهة.
-- ============================================================
